version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quicktable_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=quick_table;Username=postgres;Password=123
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"